export const sellers = [
  { id: 1, name: "Tech Haven", rating: 4.7 },
  { id: 2, name: "Gadget World", rating: 4.3 },
  { id: 3, name: "SmartBuy", rating: 4.8 },
  { id: 4, name: "ElectroMart", rating: 4.2 },
  { id: 5, name: "Device Depot", rating: 4.5 },
];
export const laptops = [
  {
    id: 1,
    title: "MacBook Pro 14",
    brand: "Apple",
    price: 1999,
    amount: 5,
    available: true,
    sellerId: 1,
  },
  {
    id: 2,
    title: "Dell XPS 13",
    brand: "Dell",
    price: 1299,
    amount: 3,
    available: true,
    sellerId: 2,
  },
  {
    id: 3,
    title: "HP Spectre x360",
    brand: "HP",
    price: 1199,
    amount: 0,
    available: false,
    sellerId: 3,
  },
  {
    id: 4,
    title: "Asus ZenBook 14",
    brand: "Asus",
    price: 999,
    amount: 7,
    available: true,
    sellerId: 4,
  },
  {
    id: 5,
    title: "Lenovo ThinkPad X1",
    brand: "Lenovo",
    price: 1499,
    amount: 2,
    available: true,
    sellerId: 5,
  },
  {
    id: 6,
    title: "Acer Swift 5",
    brand: "Acer",
    price: 899,
    amount: 0,
    available: false,
    sellerId: 1,
  },
  {
    id: 7,
    title: "MacBook Air M2",
    brand: "Apple",
    price: 1099,
    amount: 4,
    available: true,
    sellerId: 2,
  },
  {
    id: 8,
    title: "Dell Inspiron 15",
    brand: "Dell",
    price: 749,
    amount: 6,
    available: true,
    sellerId: 3,
  },
  {
    id: 9,
    title: "Asus ROG Zephyrus",
    brand: "Asus",
    price: 1799,
    amount: 1,
    available: true,
    sellerId: 4,
  },
  {
    id: 10,
    title: "HP Pavilion 14",
    brand: "HP",
    price: 649,
    amount: 0,
    available: false,
    sellerId: 5,
  },
];
